# Site settings
title: Datamx.io - La plataforma de datos abiertos de México.
email: datamx@codeandomexico.org
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pages.datamx.io" # the base hostname & protocol for your site
twitter_username: datamx_io

# Build settings
markdown: kramdown

gems:
  - jekyll-compass
